"""Client protocol: the interface used by CLI/frontends.

This is the abstract interface the sdbus client implements.  Frontends
depend only on this protocol, never on raw D-Bus values.
"""

from __future__ import annotations

from typing import Any, Protocol

from honor_control.core.models import OperationResult, SystemSnapshot


class ControlClient(Protocol):
    """The client interface used by CLI, GUI, and tray."""

    @property
    def connected(self) -> bool: ...

    async def connect(self) -> None: ...
    async def close(self) -> None: ...

    # -- Reads --
    async def get_api_version(self) -> int: ...
    async def get_schema_version(self) -> int: ...
    async def get_snapshot(self) -> SystemSnapshot: ...
    async def run_checks(self) -> dict[str, Any]: ...

    # -- Battery --
    async def set_thresholds(self, end: int, start: int) -> OperationResult: ...
    async def set_mode(self, mode: str) -> OperationResult: ...

    # -- Power --
    async def set_profile(self, profile: str) -> OperationResult: ...
    async def set_auto_switch(self, enabled: bool) -> OperationResult: ...
    async def save_power_profile(
        self,
        name: str,
        label: str,
        description: str,
        pl1_uw: int,
        pl2_uw: int,
        governor: str,
        epp: str,
        ppd_profile: str,
        turbo_enabled: bool,
        max_perf_pct: int,
    ) -> OperationResult: ...
    async def delete_power_profile(self, name: str) -> OperationResult: ...
    async def configure_auto_switch(
        self,
        enabled: bool,
        on_ac: str,
        on_battery: str,
        on_ac_script: str,
        on_battery_script: str,
    ) -> OperationResult: ...

    # -- Fan --
    async def set_stock_auto(self) -> OperationResult: ...
    async def set_curve(
        self, profile: str, points: list[tuple[int, int]]
    ) -> OperationResult: ...
    async def set_manual(self, speed: int, ttl_seconds: int) -> OperationResult: ...

    # -- Gestures --
    async def set_mapping(self, gesture_id: str, combo: str) -> OperationResult: ...
    async def set_enabled(self, gesture_id: str, enabled: bool) -> OperationResult: ...
    async def set_all_enabled(self, enabled: bool) -> OperationResult: ...
    async def set_daemon_enabled(self, enabled: bool) -> OperationResult: ...

    # -- GPU --
    async def set_mitigation_enabled(self, enabled: bool) -> OperationResult: ...

    # -- Config / diagnostics --
    async def reload(self) -> OperationResult: ...
    async def get_debug_bundle(self) -> dict[str, Any]: ...
    async def get_recent_logs(self, lines: int) -> list[str]: ...

    # -- Subscriptions --
    def on_state_changed(self, callback) -> None: ...
